DROP TABLE students IF EXISTS;

CREATE TABLE students (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(30),
  school_name  VARCHAR(30),
  favourite_subject  VARCHAR(30)
);